### ISSUE TITLE
Multiple SMTP servers

### ISSUE THREAD

**Issue by pitbullcan** [msudol/node-open-relay-mail-service#4]
Please can you give a guide on how to implement multiple smtps for relay. If possible SMTP rotation after a number of emails are
sent out.

Thanks.

**Comment by msudol** [comment]
so in the context of this application in the config, the smtp for relay is the "transporter"

    // configure the connection to the actual mail server
    // more details http://nodemailer.com/smtp/
    transporter: {
        host: 'outlook.test.local',
        port: 25,
        secure: false, // true for 465, false for other ports
        requireTLS: false
        // uncomment to use user authorization to the SMTP server
        //auth: {
        //    user: account.user, // generated ethereal user
        //    pass: account.pass // generated ethereal password
        //}  
    },


you could alter that to be an array of transporters, and then put in code cycle through them
